language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "14"
sudo: false
before_install:
  - npm config set registry https://:2020-09-02T01%3A22%3A07.505Z@time-machines-npm.sealsecurity.io/
install: npm install
script:
  - if [ "x$BUNDLER" = "x" ]; then npm test; fi
  - if [ "x$BUNDLER" != "x" ]; then npm run test-karma; fi
# only run karma tests for one node version
matrix:
  include:
  - node_js: "10"
    env: BUNDLER=webpack
  - node_js: "10"
    env: BUNDLER=browserify
notifications:
  email:
    on_success: change
    on_failure: change
